version: '3.6'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    restart: unless-stopped
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.1
    restart: unless-stopped
    ports:
      - "5601:5601"
    environment:
      - SERVER_PORT=5601
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
  pgsql-metabase-docker:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - ./postgres:/var/lib/postgresql/data
  metabase-docker:
    image: metabase/metabase
    restart: always
    ports:
      - 3002:3000
    volumes:
      - ./metabase-data:/metabase-data
    environment:
      JAVA_TOOL_OPTIONS: -Xmx4g
      MB_DB_PORT: 5432  
      MB_DB_TYPE: "${MB_DB_TYPE}" 
      MB_DB_DBNAME: "${MB_DB_DBNAME}" 
      MB_DB_USER: "${MB_DB_USER}" 
      MB_DB_PASS: "${MB_DB_PASS}" 
      MB_DB_HOST: "${MB_DB_HOST}" 
      MB_JETTY_MAXTHREADS: 300
    depends_on:
      - pgsql-metabase-docker
    links:
      - pgsql-metabase-docker

volumes:
  esdata:
