version: '3.6'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    restart: unless-stopped
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - esdata:/usr/share/elasticsearch/data
    networks:
      - kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.1
    restart: unless-stopped
    ports:
      - "5601:5601"
    environment:
      - SERVER_PORT=5601
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - kibana
  web:
    build: .
    volumes:
      - .:/myapp
    working_dir: /myapp
    command: npm start
    ports:
      - "8081:8081"
    depends_on:
      - kibana
    environment: 
      - PORT=8081
    stdin_open: true
  nginx:
    image: nginx
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - 8090:80
    networks: 
      - kibana
    depends_on:
      - kibana
volumes:
  esdata:
networks: 
  kibana: ~